[tox]
envlist = py39,py310,py311,py312,py313

[testenv]
extras = tests
allowlist_externals =
    black
    pytest
commands =
    black --diff .
    pytest --cov --cov-report=html --cov-fail-under=100
